esphome:
  name: "esphome-airstick-1"

esp32:
  board: m5stick-c
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-A81F70"
    password: "DcAizdBCTtA0"

captive_portal:
    
external_components:
  - source: github://airy10/esphome-m5stickC@master
    components: [ axp192 ]

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1
        
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1

# AXP192 power management - must be present to initialize TFT power on
sensor:
  - platform: axp192
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "M5Stick Battery Level"
      id: "m5stick_batterylevel"

  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    id: wifi_dbm
  - platform: uptime
    name: ${upper_devicename} Uptime

  - platform: senseair
    co2:
      name: "Airstick One SenseAir CO2 Value"
      id: airstickoneco2
    update_interval: 10s

# internal LED
light:
  - platform: monochromatic
    output:  builtin_led
    name: ${upper_devicename} Led
    id: led1

output:
  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: True

font:
  - file: 'fonts/OpenSans-Regular.ttf'
    id: font1
    size: 8

  - file: 'fonts/OpenSans-Regular.ttf'
    id: font2
    size: 25

  - file: 'fonts/OpenSans-Regular.ttf'
    id: font3
    size: 14

color:
    - id: color_red
      red: 100%
      green: 0%
      blue: 0%
    - id: color_green
      red: 0%
      green: 100%
      blue: 0%
    - id: color_blue
      red: 0%
      green: 0%
      blue: 100%
    - id: color_white
      red: 100%
      green: 100%
      blue: 100%

graph:
  - id: co2sensorgraph
    duration: 1h
    x_grid: 10min
    # y_grid: 1.0     
    width: 200
    height: 65
    traces:
      - sensor: airstickoneco2
        line_type: SOLID
        line_thickness: 2
        color: color_green

display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 90
    lambda: |-
      it.printf(0, 0, id(font2), color_white, "CO2: %.0f ppm", id(airstickoneco2).state);
      it.graph(2, 30, id(co2sensorgraph));
      // Print time in HH:MM format
      it.strftime(2, 95, id(font2), color_blue, TextAlign::LEFT, "%H:%M", id(sntp_time).now());

time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: sntp
    id: sntp_time

uart:
  rx_pin: G33
  tx_pin: G32
  baud_rate: 9600

